[server]
headless = true
address = "0.0.0.0"
port = 8501

[theme]
primaryColor = "#2ECC71"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#2C3E50"
font = "sans serif"

[global]
showWarningOnDirectExecution = false
