[type]
service_account = true

[google_sheets]
project_id = "nutritracker-450617"
private_key_id = "d3d77ba30964c8fb463379859afa996331e428a0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCXFMcUkdAFFMW4
3+QFAj8T27Xyws2tJTcFqOoeTi1W+5RnnYsnHf5fqCqW6F684tX6oJdORZngsBrd
PwmjzuKzpHiGtStRkrXjVKSS16j4vGTDUcCXT/9QADcW4g/+oRS1gQY4F7+l0M74
N/yD1bR9ktLPPzv+hxISkyDVrE7NDawN0SpnoSxDwus5PhhRE2P+w99V/Scoqs75
K/YltiX7HazzQfEn7pgN58RffxPCOh5EvtqhHKel3TuEqICeGu20zgFy1MGsCFdD
0+9xd+yJH0CZYJ7JHcvd1B7Ywp1DgjFDe7qsQzHpRYpAC2fYcu/L7JHMaL+iiwGM
8NqEgGFNAgMBAAECggEAB9f9z/0UAjeGXmdNVM89jB/jjeN8PymH9kTDRuiDJRlx
poGA6Hp/quK1t1kAFilmt5jf0iH977Lk6iisLPOARJhc442DXrxRsihCVRdaP/Oz
/YoAiDqQhExGj+sTroIZa6TzuDTPb+Hr5OovM38EXGKjjDv5tui3UPyPf1hvTOj8
4n/UTPMKteTZ5uBKKP0ebi36VC518LAK2X/kQK26vcTriu4XJ+aysgVFlW1tFcNs
XBhzJN9gGUb0RSzI/ObbPMDCYSysVwbv/xCofmZUDq8s5u/zM10+bbU4Td859bKM
7ikteldiWk0gOK5DIr6VRtqIKUT77QAeGJruHf2pAQKBgQDFjTTf5OvJ5q22zXuT
fGDdxFPBWscEKmNQ8UWDVbI/Le17GMwLPMixKSoRlvDYULLP21irqAXs3vMh3NAQ
Qkx35uzsoohy3iwG/HQqJ1G6VUqxMiI8d5wG3cpErbFWIc+QFTGlEw57rLyaOACV
Um8lWCGZ/11bxMytQpij7/EjzQKBgQDDx9h1o5mIqjxOgv6E4ph1zcMuG6e89VPA
4Jt93gxye4Eg0rNv3pgbbm4zY588OB7nOGU5mFSKWXAicukq0uvUmMxrFHXgTQfp
pyQ2+JqOXnkjdvrPKk/J+DPVpaESZRxn3t3haz7RHtEz6U73A4jGF92NA7HNunQG
EBuXdMmzgQKBgQC1am9cDMXbq9NrRFhvoJD0Fw8zSUHqOWLrOiYz7ca67lpf6O24
hCFpT/wqGwsiGzmaWDydpreKR1PPjRAlXj0K/y4kQT48/npAECY9b85F532oK/n0
vYKza4oMd9Wa24HZNx1YEqACQycQGM2wUvtut/hji3cYhynPEpFKO1afIQKBgDXu
JhV5xIBeDJDACuaGGONSk/Jukc0+cxzNgmewtBMRLGfjQqSNV68uw1KKncGT4Adn
hJLSAG+/5WDH8KzoPyhoEt9oWnQ4I/bcIOC3qLORGKOJUduhVytWoMi4gF811RZT
0SEYTsyCRbScDzGCGroettvyaZc3RmCpLUCSXkGBAoGAZOlPU+j7FGJBBI8rC3sY
wCBO26JlOvMD/rJKaHpXvpmb6dCyJpaT6dg9+LfKE0HQYdACR7RkbK9s6mRG09sQ
9rb0S1X29tqxkr5Td8FxrWgYd67Al+Kf9+E1MKNCPmolaoYYs9Vu8541YaEY1zj5
i3kbqjKe2XpaKS94unlcoVU=
-----END PRIVATE KEY-----"""

client_email = "calorie-tracker@nutritracker-450617.iam.gserviceaccount.com"
client_id = "100756986424596362972"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/calorie-tracker%40nutritracker-450617.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
